[package]
org = "choreo"
name = "consent_service"
version = "1.2.1"
export = ["consent_service"]
distribution = "2201.2.3"
keywords = ["Kind/Sample","Type/RestApi","Category/Service","Internal/http"]
icon = "docs/icon.png"

[build-options]
observabilityIncluded = true
